server.name: kibana
server.host: 0.0.0.0
server.port: 5601

elasticsearch.hosts: ["http://elasticsearch:9200"]
elasticsearch.username: kibana_system
elasticsearch.password: ${KIBANA_SYSTEM_PASSWORD}

xpack.encryptedSavedObjects.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
xpack.security.encryptionKey: ${KIBANA_SECURITY_KEY}
xpack.reporting.encryptionKey: ${KIBANA_REPORTING_KEY}

monitoring.ui.container.elasticsearch.enabled: true
